# kubectl apply -f elasticsearch.yaml
# https://blogs.msdn.microsoft.com/atverma/2018/09/24/azure-kubernetes-service-aks-deploying-elasticsearch-logstash-and-kibana-elk-and-consume-messages-from-azure-event-hub/
apiVersion: v1
kind: ConfigMap
metadata:
  name: inf-elasticsearch-configmap
  namespace: default
data:
  elasticsearch.yml: |
    cluster.name: "inf-elasticsearch-cluster"
    network.host: 0.0.0.0
    discovery.zen.minimum_master_nodes: 2
    discovery.zen.ping.unicast.hosts: inf-elasticsearch
    node.max_local_storage_nodes: 2
    xpack.monitoring.collection.enabled: true
---
apiVersion: v1
kind: Service
metadata:
  name: inf-elasticsearch
  labels:
    app: inf
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 9200
  - name: transport
    port: 9300
  selector:
    app: inf
    tier: elasticsearch
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: inf-elasticsearch
  labels:
    app: inf
spec:
  serviceName: inf-elasticsearch
  replicas: 2
  selector:
    matchLabels:
      app: inf
      tier: elasticsearch
  template:
    metadata:
      labels:
        app: inf
        tier: elasticsearch
    spec:
      terminationGracePeriodSeconds: 15
      initContainers:
      - name: increase-the-vm-max-map-count
        image: busybox
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: inf-elasticsearch
        image: elasticsearch:6.5.1
        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 1Gi
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        env:
        - name: cluster.name
          value: "inf-elasticsearch-cluster"
        - name: "TAKE_FILE_OWNERSHIP"
          value: “1”
        livenessProbe:
          #httpGet:
          #  path: /_cluster/health?local=true
          #  port: http
          tcpSocket:
            port: transport
          initialDelaySeconds: 90
        readinessProbe:
          #httpGet:
          #  path: /_cluster/health
          #  port: http
          tcpSocket:
            port: transport
          initialDelaySeconds: 20
        volumeMounts:
        - name: inf-elasticsearch-data-claim
          mountPath: /usr/share/elasticsearch/data
        - name: inf-elasticsearch-configmap
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
      volumes:
      - name: inf-elasticsearch-configmap
        configMap:
            name: inf-elasticsearch-configmap
  volumeClaimTemplates:
  - metadata:
      name: inf-elasticsearch-data-claim
    spec:
      accessModes: 
        - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
