# docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:6.5.4
# https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
# sudo sysctl -w vm.max_map_count=262144
# https://stackoverflow.com/questions/34658836/docker-is-in-volume-in-use-but-there-arent-any-docker-containers#42116347
# docker stop $(docker ps -aq)
# docker rm $(docker ps -aq)
# docker network prune -f
# docker volume rm $(docker volume ls --filter dangling=true -q)
# Kibana: http://localhost:5601
# phpMySQL: http://localhost:8096 sway veJxEkenwr7mmC2o
# phpMySQL Accounts: http://localhost:8097 sway veJxEkenwr7mmC2o
# phpMySQL Proposals: http://localhost:8098 sway veJxEkenwr7mmC2o
# https://stackoverflow.com/questions/22944631/how-to-get-the-ip-address-of-the-docker-host-from-inside-a-docker-container
# docker run -i -t alpine /bin/bash
# host.docker.internal on OSX or 172.17.0.1 on Linux
# 127.0.0.1 for direct from host
# Troubleshooting:
# sway_elasticsearch2     | [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
# sudo sysctl -w vm.max_map_count=262144
# sudo nano /etc/sysctl.conf
# vm.max_map_count=262144
version: '3.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    container_name: sway_elasticsearch
    restart: always
    environment:
      - cluster.name=sway-dev
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data_elasticsearch1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    container_name: sway_elasticsearch2
    depends_on:
      - elasticsearch
    restart: always
    environment:
      - cluster.name=sway-dev
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data_elasticsearch2:/usr/share/elasticsearch/data
  mariadb_general:
    image: mariadb:10.5
    container_name: sway_mariadb_general
    volumes:
      - data_sql_general:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 04KWKM2u6bXUj9N9
      MYSQL_DATABASE: sway
      MYSQL_USER: sway
      MYSQL_PASSWORD: veJxEkenwr7mmC2o
    ports:
      - 3306:3306
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
  mariadb_accounts:
    image: mariadb:10.5
    container_name: sway_mariadb_accounts
    volumes:
      - data_sql_accounts:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 04KWKM2u6bXUj9N9
      MYSQL_DATABASE: sway
      MYSQL_USER: sway
      MYSQL_PASSWORD: veJxEkenwr7mmC2o
    ports:
      - 3307:3306
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
  mariadb_proposals:
    image: mariadb:10.5
    container_name: sway_mariadb_proposals
    volumes:
      - data_sql_proposals:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 04KWKM2u6bXUj9N9
      MYSQL_DATABASE: sway
      MYSQL_USER: sway
      MYSQL_PASSWORD: veJxEkenwr7mmC2o
    ports:
      - 3308:3306
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
  kibana:
    image: kibana:6.5.4
    depends_on:
      - elasticsearch
      - elasticsearch2
    restart: always
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 5601:5601
  phpmyadmin_general:
    image: phpmyadmin/phpmyadmin:4.8
    depends_on:
      - mariadb_general
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 04KWKM2u6bXUj9N9
      PMA_HOST: mariadb_general
      PMA_PORT: 3306
      PMA_PASSWORD: veJxEkenwr7mmC2o
    ports:
      - 8096:80
  phpmyadmin_accounts:
    image: phpmyadmin/phpmyadmin:4.8
    depends_on:
      - mariadb_accounts
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 04KWKM2u6bXUj9N9
      PMA_HOST: mariadb_accounts
      PMA_PORT: 3306
      PMA_PASSWORD: veJxEkenwr7mmC2o
    ports:
      - 8097:80
  phpmyadmin_proposals:
    image: phpmyadmin/phpmyadmin:4.8
    depends_on:
      - mariadb_proposals
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 04KWKM2u6bXUj9N9
      PMA_HOST: mariadb_proposals
      PMA_PORT: 3306
      PMA_PASSWORD: veJxEkenwr7mmC2o
    ports:
      - 8098:80
volumes:
  data_elasticsearch1:
    driver: local
  data_elasticsearch2:
    driver: local
  data_sql_general:
    driver: local
  data_sql_accounts:
    driver: local
  data_sql_proposals:
    driver: local
