name: sample_api_direct
description: Direct API usage sample. Test suite.
version: 0.1.0
homepage: https://www.infmarketplace.com
author: Jan Boon <jan.boon@kaetemi.be>
publish_to: none

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  sway_common:
    path: ../sway_common/
  logging: ^0.11.3+2

dev_dependencies:
  test: ^1.0.0
  faker: ^1.0.0
  mime: ^0.9.6+2

dependency_overrides:
  # analyzer: ^0.32.4 # Force upgrade of reflectable, used by pointycastle
