name: inf_server_explore
description: INF Server Explore service.
version: 3.0.1
homepage: https://www.infmarketplace.com
author: Jan Boon <jan.boon@kaetemi.be>
publish_to: none

environment:
  sdk: '>=2.0.0-dev.58.0 <3.0.0'

dependencies:
  sway_common:
    path: ../sway_common/
  logging: ^0.11.3+2
  pedantic: ^1.4.0
  http_client: ^0.5.0
  http: ^0.12.0+1
  synchronized: ^1.5.1
  mime: ^0.9.6+2
  quiver: ^2.0.0+1
  s2geometry: ^0.1.1
  geohash: ^0.2.1

dev_dependencies:
  test: ^1.0.0

dependency_overrides:
  # analyzer: ^0.32.4 # Force upgrade of reflectable, used by pointycastle
