name: inf
description: INFluencers

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

# Dependencies are ordered alphabethically or grouped if it makes sense  

dependencies:
  connectivity: any
  decimal: any
  firebase_messaging: ^2.0.0
  flutter_local_notifications: ^0.3.7
  get_it: any
  protobuf: ^0.10.4
  permission_handler: any
  rxdart: any
  rx_command: any
  shared_preferences: any

  sentry: any
  package_info: any
  device_info: any
  system_info: any

  wstalk:
    git:
      url: https://github.com/nbspou/wstalk.git
      ref: master


  flutter:
    sdk: flutter
  cupertino_icons: any
  # cloud_firestore: any 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - assets/images/
   - assets/mockdata/
