name: inf_config
description: A starting point for Dart libraries or applications.
version: 1.0.14
homepage: https://www.infmarketplace.com
author: Jan Boon <kaetemi@no-break.space>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  protobuf: ^0.10.4
  ini: ^2.0.1
  fixnum: ^0.10.9
  dospace: ^0.10.7
  inf_common:
    git: 
      url: git@github.com:infmarketplace/inf_common.git
      ref: af90e50

dev_dependencies:
  test: ^1.0.0
