name: inf
description: INFluencers

version: 1.0.0+1

environment:
  sdk: ">=2.0.0 <3.0.0"

# Dependencies are ordered alphabetically or grouped if it makes sense

dependencies:
  connectivity: any
  decimal: any
  flutter_map: any
  flutter_page_indicator: any 
  flutter_svg: any
  get_it: any
  intl: any
  location: 
    git: https://github.com/slightfoot/flutter_location
  rxdart: any
  rx_command: any
  path_provider: any
  url_launcher: any

  sentry: any
  package_info: any
  system_info: any

  flutter:
    sdk: flutter

  inf_common:
    git: 
      url: git@github.com:infmarketplace/inf_common.git
      ref: af897a8e081810248b23b7f756544989c8601c49
  switchboard: ^2.0.5
  firebase_messaging: ^2.0.0
  flutter_local_notifications: ^0.4.2
  device_info: ^0.3.0
  shared_preferences: ^0.4.2
  synchronized: ^1.5.1
  logging: ^0.11.3+2
  
  cupertino_icons: any
  font_awesome_flutter: any

  # cloud_firestore: any
  pedantic: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - assets/images/
  - assets/mockdata/

  fonts:
  - family: MavenPro
    fonts:
    - asset: assets/fonts/MavenPro-Regular.ttf
    - asset: assets/fonts/MavenPro-Medium.ttf
      weight: 500
    - asset: assets/fonts/MavenPro-Bold.ttf
      weight: 700
