name: inf
description: INFluencers

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  get_it: any

  sentry: any
  package_info: any
  device_info: any
  system_info: any
  connectivity: any

  flutter:
    sdk: flutter
  cupertino_icons: any
  cloud_firestore: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - assets/images/
