name: inf
description: INFluencers

version: 1.0.0+2

environment:
  sdk: ">=2.2.2 <3.0.0"

# Dependencies are ordered alphabetically or grouped if it makes sense

dependencies:
  logging: 0.11.3+2
  connectivity: 0.4.3+1
  decimal: 0.3.3
  firebase_messaging: 5.0.1+1
  flutter_map:
    git: https://github.com/slightfoot/flutter_map.git
  flutter_page_indicator: 0.0.3
  flutter_svg: 0.13.0+1
  flutter_webview_plugin: 0.3.5
  get_it: 1.0.3+1
  http: 0.12.0+2
  image_picker: 0.6.0+7
  image: 2.1.1
  intl: 0.15.8
  location:
    git: https://github.com/slightfoot/flutter_location.git
  oauth1: 1.0.4
  rxdart: 0.22.0
  rx_command: 4.3.1
  pedantic: 1.5.0
  path_provider: 0.5.0+1
  uni_links: 0.2.0
  url_launcher: 5.0.2
  shared_preferences: 0.5.2+1
  mime: 0.9.6+2
  provider: 2.0.1

  sentry: 2.2.0
  device_info: 0.4.0+1
  package_info: 0.4.0+3
  system_info: 0.1.1

  flutter:
    sdk: flutter

  email_launcher:
    git: https://github.com/infmarketplace/plugin_email_launcher.git

  inf_api_client:
    git:
      url: https://github.com/infmarketplace/inf_server.git
      ref: dev
      path: src/inf_api_client

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/root.crt
    - assets/images/
    - assets/mockdata/
    - assets/mockdata/category_icons/
    - assets/mockdata/delivery_type_icons/
    - assets/mockdata/social_media_icons/

  fonts:
    - family: MavenPro
      fonts:
        - asset: assets/fonts/mavenpro-regular.ttf
        - asset: assets/fonts/mavenpro-medium.ttf
          weight: 500
        - asset: assets/fonts/mavenpro-bold.ttf
          weight: 700
