name: inf
description: INFluencers

version: 1.0.0+2

environment:
  sdk: ">=2.0.0 <3.0.0"

# Dependencies are ordered alphabetically or grouped if it makes sense

dependencies:
  connectivity: any
  decimal: any
  firebase_messaging: any
  flutter_map: any
  flutter_page_indicator: any
  flutter_secure_storage: any
  flutter_svg: any
  flutter_webview_plugin: any
  get_it: any
  http: any
  image_picker: any
  image: any
  intl: any
  location:
    git: https://github.com/slightfoot/flutter_location.git
  oauth1: any
  rxdart: any
  rx_command: any
  pedantic: any
  path_provider: any
  uni_links: any
  url_launcher: any
  quiver: any
  shared_preferences: any

  sentry: any
  device_info: any
  package_info: any
  system_info: any

  flutter:
    sdk: flutter

  inf_api_client:
    git:
       url: https://github.com/infmarketplace/inf_server.git
       ref: alpha
       path: src/inf_api_client

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - assets/images/
  - assets/mockdata/
  - assets/mockdata/category_icons/
  - assets/mockdata/delivery_type_icons/
  - assets/mockdata/social_media_icons/

  fonts:
  - family: MavenPro
    fonts:
    - asset: assets/fonts/mavenpro-regular.ttf
    - asset: assets/fonts/mavenpro-medium.ttf
      weight: 500
    - asset: assets/fonts/mavenpro-bold.ttf
      weight: 700
