name: inf_common
description: INF Common Protocol files. Shared data structures and enumerations. 
version: 1.2.23
homepage: https://www.infmarketplace.com
author: Jan Boon <kaetemi@no-break.space>
publish_to: none

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  protobuf: ^0.10.5

#dev_dependencies:
#  test: ^1.0.0
