name: inf_server_api
description: INF Server API service.
version: 3.0.11
homepage: https://www.infmarketplace.com
author: Jan Boon <jan.boon@kaetemi.be>
publish_to: none

environment:
  sdk: '>=2.0.0-dev.58.0 <3.0.0'

dependencies:
  inf_common:
    git: 
      url: git@github.com:infmarketplace/inf_common.git
      ref: fb9a3e0e8ccfeb3bb18a55a8b3ed195f26f402b2
  logging: ^0.11.3+2
  pedantic: ^1.4.0
  # crypto: ^2.0.6
  # pointycastle: ^1.0.0-rc2
  http_client: ^0.5.0
  synchronized: ^1.5.1
  mime: ^0.9.6+2
  quiver: ^2.0.0+1
  sqljocky5: # ^1.0.0
    git:
      url: https://github.com/nbspou/sqljocky5.git
      ref: 1feb53e331bf6405fcd8b40362922096f950dad7
  # switchboard: ^2.0.11
  # grpc: ^1.0.0
  oauth1:
    git:
      url: https://github.com/nbspou/dart-oauth1.git
      ref: 8e0a1ac7054e3c03a3d10f14721265dd51b88362
  dospace: ^0.11.0
  s2geometry: ^0.1.1
  geohash: ^0.2.1

dev_dependencies:
  test: ^1.0.0

dependency_overrides:
  # analyzer: ^0.32.4 # Force upgrade of reflectable, used by pointycastle
