name: inf_server_api
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Jan Boon <email@example.com>

environment:
  sdk: '>=2.0.0-dev.58.0 <3.0.0'

dependencies:
  inf_common:
    git: 
      url: git@github.com:infmarketplace/inf_common.git
      ref: c3c1e55c96e63e0faaaa5cc4862a25c58cd44a82
  logging: ^0.11.3+2
  # crypto: ^2.0.6
  # pointycastle: ^1.0.0-rc2
  http_client: ^0.5.0
  synchronized: ^1.5.1
  mime: ^0.9.6+2
  quiver: ^2.0.0+1
  sqljocky5: # ^1.0.0
    path: ../sqljocky5/
  switchboard: ^2.0.5
  oauth1:
    path: ../dart-oauth1/
  dospace: ^0.11.0
  s2geometry: ^0.1.1

dev_dependencies:
  test: ^1.0.0

dependency_overrides:
  # analyzer: ^0.32.4 # Force upgrade of reflectable, used by pointycastle
