name: inf_server_api
description: INF Server API service.
version: 2.0.0
homepage: https://www.infmarketplace.com
author: Jan Boon <kaetemi@no-break.space>
publish_to: none

environment:
  sdk: '>=2.0.0-dev.58.0 <3.0.0'

dependencies:
  inf_common:
    git: 
      url: git@github.com:infmarketplace/inf_common.git
      ref: 38bd60e405335160cfc858522161e5928516c373
  logging: ^0.11.3+2
  # crypto: ^2.0.6
  # pointycastle: ^1.0.0-rc2
  http_client: ^0.5.0
  synchronized: ^1.5.1
  mime: ^0.9.6+2
  quiver: ^2.0.0+1
  sqljocky5: # ^1.0.0
    path: ../sqljocky5/
  switchboard: ^2.0.9
  oauth1:
    path: ../dart-oauth1/
  dospace: ^0.11.0
  s2geometry: ^0.1.1
  geohash: ^0.2.1

dev_dependencies:
  test: ^1.0.0

dependency_overrides:
  # analyzer: ^0.32.4 # Force upgrade of reflectable, used by pointycastle
