// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: net_get_service.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace InfX {

  /// <summary>Holder for reflection information generated from net_get_service.proto</summary>
  public static partial class NetGetServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for net_get_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static NetGetServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVuZXRfZ2V0X3NlcnZpY2UucHJvdG8SA2luZhoWbmV0X2dldF9wcm90b2J1",
            "Zi5wcm90bzLDAQoNTmV0R2V0U2VydmljZRI6CgpnZXRBY2NvdW50EhUuaW5m",
            "Lk5ldEdldEFjY291bnRSZXEaFS5pbmYuTmV0R2V0QWNjb3VudFJlcxI0Cghn",
            "ZXRPZmZlchITLmluZi5OZXRHZXRPZmZlclJlcRoTLmluZi5OZXRHZXRPZmZl",
            "clJlcxJACgxnZXRBcHBsaWNhbnQSFy5pbmYuTmV0R2V0QXBwbGljYW50UmVx",
            "GhcuaW5mLk5ldEdldEFwcGxpY2FudFJlc0IHqgIESW5mWGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::InfX.NetGetProtobufReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
