name: inf_api_client

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  async: any
  grpc: ^1.0.0
  #grpc:
  #  git:
  #    url: https://github.com/slightfoot/grpc-dart.git
  protobuf: 0.13.9

dev_dependencies:
  test: any