version: '3.3'
services:
  sample_jwt_envoy:
    image: envoyproxy/envoy:latest
    network_mode: host
    # ports:
    # - "127.0.0.1:7901:7901"
    # - "127.0.0.1:7902:7902"
    restart: always
    volumes:
    - ./envoy.yaml:/etc/envoy/envoy.yaml
    - ./jwks_public.json:/etc/envoy/jwks/jwks_public.json
