name: inf
description: One million dollars

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  font_awesome_flutter: ^6.0.0

  protobuf: ^0.7.2

  circle_indicator: ^0.0.7

  flutter_webview_plugin: 0.1.5
  http: ^0.11.3+13

  # Device info, used during device registration
  device_info: ^0.2.1
  shared_preferences: ^0.4.2
  pointycastle: ^1.0.0-rc2

  # oauth1:
  #   path: ../dart-oauth1/

  flutter_map: # ^0.0.4
    path: ../flutter_map/flutter_map/

  wstalk:
    path: ../wstalk/
  
  # 0.4.1 crashes
  image_picker: 0.3.1

# dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  
# Search bar
  flutter_search_bar: "^2.0.2"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  assets:
    - assets/config.bin
    - assets/logo_appbar.png
    - assets/placeholder_photo.png
    - assets/placeholder_photo_select.png

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
