name: inf
description: One million dollars

dependencies:
  flutter:
    sdk: flutter

  fixnum: any
  
  inf_common:
    git: 
      url: git@github.com:infmarketplace/inf_common.git
      ref: 5d4c9d2d78efbb4b71118869788942ff8aeff319

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  font_awesome_flutter: ^8.0.0

  firebase_messaging: ^2.0.0
  flutter_local_notifications: ^0.4.2

  protobuf: ^0.10.5

  circle_indicator:
    git: https://github.com/nbspou/circle_indicator.git

  flutter_webview_plugin: ^0.2.1+2
  cached_network_image: ^0.4.2
  flutter_svg: ^0.7.0+1

  # Device info, used during device registration
  device_info: ^0.3.0
  shared_preferences: ^0.4.2
  # pointycastle: ^1.0.0-rc4
  synchronized: ^1.5.1
  path_provider: ^0.4.1
  logging: ^0.11.3+2

  flutter_map: ^0.1.4

  switchboard: ^2.0.5

  geolocator: ^2.1.0
  url_launcher: ^4.0.1
  
  image_picker: ^0.4.7
  mime: ^0.9.6+2
  
  crypto: ^2.0.6

# dev_dependencies:
  # flutter_test:
  #   sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  assets:
    - assets/images/
    - assets/config.bin
    - assets/logo_appbar.png
    - assets/logo_appbar_ext_gray.png
    - assets/placeholder_photo.png
    - assets/placeholder_photo_select.png
    - assets/placeholder_map_tile.png
    - assets/default_avatar_influencer.png
    - assets/default_avatar_business.png

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
  fonts:
  - family: MavenPro
    fonts:
    - asset: assets/fonts/MavenPro-Regular.ttf
    - asset: assets/fonts/MavenPro-Medium.ttf
      weight: 500
    - asset: assets/fonts/MavenPro-Bold.ttf
      weight: 700
