# https://joosten-industries.nl/2018/11/11/setting-up-a-kubernetes-cluster-with-digital-ocean-and-traefik/
apiVersion: v1
kind: Service
metadata:
  name: inf-loadbalancer
spec:
  type: LoadBalancer
  ports:
    # - name: http
    #   targetPort: 8090
    #   port: 80
    - name: https
      targetPort: 8090
      port: 443
  selector:
    app: inf
    tier: server-api
