name: sample_jws
description: JWT sample
version: 1.0.0
homepage: https://www.infmarketplace.com
author: Jan Boon <jan.boon@kaetemi.be>
publish_to: none

environment:
  sdk: '>=2.0.0-dev.58.0 <3.0.0'

dependencies:
  grpc: ^1.0.0
  protobuf: "0.11.0"

dev_dependencies:
  test: ^1.0.0

dependency_overrides:
  # analyzer: ^0.32.4 # Force upgrade of reflectable, used by pointycastle
