name: sample_jwt
description: JWT sample
version: 0.1.0
homepage: https://www.infmarketplace.com
author: Jan Boon <jan.boon@kaetemi.be>
publish_to: none

environment:
  sdk: '>=2.0.0-dev.58.0 <3.0.0'

dependencies:
  inf_common:
    git: 
      url: git@github.com:infmarketplace/inf_common.git
      ref: aae9e84a730842a2967da434d58bf5c6cf95ed49 # Specific version to match protobuf version
  grpc: ^1.0.0
  protobuf: "0.11.0" # Must rebuild protos if mismatching with inf_common
  logging: ^0.11.3+2

dev_dependencies:
  test: ^1.0.0

dependency_overrides:
  # analyzer: ^0.32.4 # Force upgrade of reflectable, used by pointycastle
