name: config
description: INF configuration generator.
version: 0.0.1
homepage: https://github.com/nbspou/dospace
author: NO-BREAK SPACE OÜ <support@no-break.space>

environment:
  sdk: '>=2.0.0-dev.58.0 <3.0.0'

dependencies:
  protobuf: ^0.9.0
  ini: ^1.1.0
  fixnum: ^0.10.7
  dospace: ^0.9.4
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
