//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace infx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("infx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi there!.
        /// </summary>
        internal static string OnboardingHi {
            get {
                return ResourceManager.GetString("OnboardingHi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am a business.
        /// </summary>
        internal static string OnboardingSelectBusiness {
            get {
                return ResourceManager.GetString("OnboardingSelectBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am an influencer.
        /// </summary>
        internal static string OnboardingSelectInfluencer {
            get {
                return ResourceManager.GetString("OnboardingSelectInfluencer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do you see yourself?.
        /// </summary>
        internal static string OnboardingSelectType {
            get {
                return ResourceManager.GetString("OnboardingSelectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1/3.
        /// </summary>
        internal static string OnboardingStep1 {
            get {
                return ResourceManager.GetString("OnboardingStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onboarding.
        /// </summary>
        internal static string OnboardingTitle {
            get {
                return ResourceManager.GetString("OnboardingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What are you looking for?.
        /// </summary>
        internal static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
    }
}
