name: api
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Jan Boon <email@example.com>

environment:
  sdk: '>=2.0.0-dev.58.0 <3.0.0'

dependencies:
  protobuf: ^0.7.2
  sqljocky5: # ^1.0.0
    path: ../sqljocky5/
#  postgres: ^1.0.0-beta.1

dev_dependencies:
  test: ^1.0.0
