name: api
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Jan Boon <email@example.com>

environment:
  sdk: '>=2.0.0-dev.58.0 <3.0.0'

dependencies:
  protobuf: ^0.9.0+1
  logging: ^0.11.3+2
  # crypto: ^2.0.6
  pointycastle: ^1.0.0-rc2
  http_client: ^0.4.4+1
  synchronized: ^1.5.1
  mime: ^0.9.6+2
  sqljocky5: # ^1.0.0
    path: ../sqljocky5/
  wstalk:
    path: ../wstalk/
  oauth1:
    path: ../dart-oauth1/
  dospace:
    path: ../dospace/

dev_dependencies:
  test: ^1.0.0

dependency_overrides:
  analyzer: ^0.32.4 # Force upgrade of reflectable, used by pointycastle
